# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleX_cpp <- function(X, tol = 1e-10) {
    .Call(`_fastfrechet_scaleX_cpp`, X, tol)
}

scaleXZ_cpp <- function(X, Z, tol = 1e-10) {
    .Call(`_fastfrechet_scaleXZ_cpp`, X, Z, tol)
}

monotoneQP_cpp <- function(Y, C_init, lower, upper, eps = 1e-10) {
    .Call(`_fastfrechet_monotoneQP_cpp`, Y, C_init, lower, upper, eps)
}

XDXt <- function(X, d) {
    .Call(`_fastfrechet_XDXt`, X, d)
}

projA0 <- function(v, h) {
    .Call(`_fastfrechet_projA0`, v, h)
}

FRiSO_GSD <- function(X, Y, gamma_init, tauseq, nudge, lower = 0, upper = 1, alpha = 1, eps = 0.0001, max_theta = 0.78539816, impulse = 1, max_iter = 1000L) {
    .Call(`_fastfrechet_FRiSO_GSD`, X, Y, gamma_init, tauseq, nudge, lower, upper, alpha, eps, max_theta, impulse, max_iter)
}

